services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: anil_kumar_portfolio
    ports:
      - "8085:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
