apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio
  namespace: personal
  labels:
    app: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
      - name: portfolio
        image: portfolio:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: SMTP_HOST
          value: "smtp.office365.com"
        - name: SMTP_PORT
          value: "587"
        - name: SMTP_USER
          value: "anil-kumar.bhutale@outlook.com"
        - name: SMTP_PASS
          value: ""
        - name: CONTACT_RECEIVER_EMAIL
          value: "anil-kumar.bhutale@outlook.com"
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: portfolio
  namespace: personal
  labels:
    app: portfolio
spec:
  selector:
    app: portfolio
  ports:
  - port: 3000
    targetPort: 3000
